title = "bheisler.github.io"
baseurl = "https://bheisler.github.io"
languageCode = "en-us"
paginate = 10

enableRobotsTxt = true
googleAnalytics = "UA-96560207-1"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
    name = "All"
    identifier = "all"
    url = "/"

[[menu.main]]
    name = "Code"
    identifier = "code"
    url = "/categories/code/"

[[menu.main]]
    name = "Props"
    identifier = "props"
    url = "/categories/props/"

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/about/"
